language: bash
services: docker

env:
  - VARIANT=php5.6/apache
  - VARIANT=php5.6/fpm
  - VARIANT=php5.6/fpm-alpine
  - VARIANT=php5.6/cli
  - VARIANT=php7.0/apache
  - VARIANT=php7.0/fpm
  - VARIANT=php7.0/fpm-alpine
  - VARIANT=php7.0/cli
  - VARIANT=php7.1/apache
  - VARIANT=php7.1/fpm
  - VARIANT=php7.1/fpm-alpine
  - VARIANT=php7.1/cli

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VARIANT"
  - slash='/'; image="wordpress:${VARIANT//$slash/-}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
